// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contact/contact.proto

package contact

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddContactReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContactReq) Reset()         { *m = AddContactReq{} }
func (m *AddContactReq) String() string { return proto.CompactTextString(m) }
func (*AddContactReq) ProtoMessage()    {}
func (*AddContactReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f68fe29e5220f006, []int{0}
}

func (m *AddContactReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactReq.Unmarshal(m, b)
}
func (m *AddContactReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactReq.Marshal(b, m, deterministic)
}
func (m *AddContactReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactReq.Merge(m, src)
}
func (m *AddContactReq) XXX_Size() int {
	return xxx_messageInfo_AddContactReq.Size(m)
}
func (m *AddContactReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactReq proto.InternalMessageInfo

func (m *AddContactReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddContactReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type AddContactRep struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContactRep) Reset()         { *m = AddContactRep{} }
func (m *AddContactRep) String() string { return proto.CompactTextString(m) }
func (*AddContactRep) ProtoMessage()    {}
func (*AddContactRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_f68fe29e5220f006, []int{1}
}

func (m *AddContactRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactRep.Unmarshal(m, b)
}
func (m *AddContactRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactRep.Marshal(b, m, deterministic)
}
func (m *AddContactRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactRep.Merge(m, src)
}
func (m *AddContactRep) XXX_Size() int {
	return xxx_messageInfo_AddContactRep.Size(m)
}
func (m *AddContactRep) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactRep.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactRep proto.InternalMessageInfo

func (m *AddContactRep) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetContactReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactReq) Reset()         { *m = GetContactReq{} }
func (m *GetContactReq) String() string { return proto.CompactTextString(m) }
func (*GetContactReq) ProtoMessage()    {}
func (*GetContactReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f68fe29e5220f006, []int{2}
}

func (m *GetContactReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactReq.Unmarshal(m, b)
}
func (m *GetContactReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactReq.Marshal(b, m, deterministic)
}
func (m *GetContactReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactReq.Merge(m, src)
}
func (m *GetContactReq) XXX_Size() int {
	return xxx_messageInfo_GetContactReq.Size(m)
}
func (m *GetContactReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactReq proto.InternalMessageInfo

func (m *GetContactReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Contact struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_f68fe29e5220f006, []int{3}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Contact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contact) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ContactList struct {
	Contact              []*Contact `protobuf:"bytes,1,rep,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ContactList) Reset()         { *m = ContactList{} }
func (m *ContactList) String() string { return proto.CompactTextString(m) }
func (*ContactList) ProtoMessage()    {}
func (*ContactList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f68fe29e5220f006, []int{4}
}

func (m *ContactList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactList.Unmarshal(m, b)
}
func (m *ContactList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactList.Marshal(b, m, deterministic)
}
func (m *ContactList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactList.Merge(m, src)
}
func (m *ContactList) XXX_Size() int {
	return xxx_messageInfo_ContactList.Size(m)
}
func (m *ContactList) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactList.DiscardUnknown(m)
}

var xxx_messageInfo_ContactList proto.InternalMessageInfo

func (m *ContactList) GetContact() []*Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type SearchContactReq struct {
	Q                    string   `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchContactReq) Reset()         { *m = SearchContactReq{} }
func (m *SearchContactReq) String() string { return proto.CompactTextString(m) }
func (*SearchContactReq) ProtoMessage()    {}
func (*SearchContactReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f68fe29e5220f006, []int{5}
}

func (m *SearchContactReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchContactReq.Unmarshal(m, b)
}
func (m *SearchContactReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchContactReq.Marshal(b, m, deterministic)
}
func (m *SearchContactReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchContactReq.Merge(m, src)
}
func (m *SearchContactReq) XXX_Size() int {
	return xxx_messageInfo_SearchContactReq.Size(m)
}
func (m *SearchContactReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchContactReq.DiscardUnknown(m)
}

var xxx_messageInfo_SearchContactReq proto.InternalMessageInfo

func (m *SearchContactReq) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchContactReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchContactReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func init() {
	proto.RegisterType((*AddContactReq)(nil), "AddContactReq")
	proto.RegisterType((*AddContactRep)(nil), "AddContactRep")
	proto.RegisterType((*GetContactReq)(nil), "GetContactReq")
	proto.RegisterType((*Contact)(nil), "Contact")
	proto.RegisterType((*ContactList)(nil), "ContactList")
	proto.RegisterType((*SearchContactReq)(nil), "SearchContactReq")
}

func init() { proto.RegisterFile("contact/contact.proto", fileDescriptor_f68fe29e5220f006) }

var fileDescriptor_f68fe29e5220f006 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0x84, 0x30,
	0x10, 0x86, 0x53, 0x10, 0x71, 0x67, 0x17, 0xa2, 0x13, 0x4d, 0x08, 0x17, 0x37, 0x3d, 0x98, 0x35,
	0x31, 0x55, 0xd7, 0x93, 0x47, 0xb3, 0x07, 0x13, 0xe3, 0x89, 0x7d, 0x02, 0x84, 0xc6, 0x6d, 0x22,
	0x50, 0xa0, 0xf1, 0x59, 0x7c, 0x5c, 0x43, 0x29, 0x4b, 0x6b, 0x3c, 0xd1, 0x99, 0x9f, 0xce, 0xff,
	0xcd, 0x5f, 0xb8, 0x2a, 0x9a, 0x5a, 0xe5, 0x85, 0xba, 0x37, 0x5f, 0x26, 0xbb, 0x46, 0x35, 0xf4,
	0x19, 0xa2, 0x97, 0xb2, 0xdc, 0x8d, 0xbd, 0x8c, 0xb7, 0x88, 0x70, 0x52, 0xe7, 0x15, 0x4f, 0xc8,
	0x9a, 0x6c, 0x16, 0x99, 0x3e, 0xe3, 0x25, 0x04, 0xf2, 0xd0, 0xd4, 0x3c, 0xf1, 0x74, 0x73, 0x2c,
	0xe8, 0xad, 0x7b, 0x55, 0x62, 0x02, 0x61, 0xc5, 0xfb, 0x3e, 0xff, 0x9c, 0x6e, 0x4f, 0x25, 0xbd,
	0x86, 0xe8, 0x95, 0x2b, 0xcb, 0x25, 0x06, 0x4f, 0x94, 0xfa, 0xaf, 0x20, 0xf3, 0x44, 0x49, 0x77,
	0x10, 0x1a, 0xd5, 0x92, 0x16, 0x83, 0x74, 0x04, 0xf2, 0xfe, 0x03, 0xf2, 0x6d, 0xa0, 0x47, 0x58,
	0x9a, 0x21, 0xef, 0xa2, 0x57, 0x48, 0x21, 0x34, 0xbb, 0x26, 0x64, 0xed, 0x6f, 0x96, 0xdb, 0x33,
	0x36, 0x11, 0x4c, 0x02, 0x7d, 0x83, 0xf3, 0x3d, 0xcf, 0xbb, 0xe2, 0x60, 0xb1, 0xad, 0x80, 0xb4,
	0xc6, 0x9f, 0xb4, 0x83, 0xd5, 0x97, 0xa8, 0x84, 0xd2, 0xfe, 0x41, 0x36, 0x16, 0x03, 0x94, 0x1c,
	0xf6, 0xf4, 0x75, 0x53, 0x9f, 0xb7, 0x3f, 0x04, 0x62, 0x33, 0x66, 0xcf, 0xbb, 0x6f, 0x51, 0x70,
	0xbc, 0x03, 0x98, 0x23, 0xc2, 0x98, 0x39, 0x51, 0xa7, 0x6e, 0x2d, 0xf1, 0x06, 0x60, 0x4e, 0x09,
	0x63, 0xe6, 0x44, 0x96, 0x1e, 0xe9, 0xf1, 0x01, 0x22, 0x07, 0x1a, 0x2f, 0xd8, 0xdf, 0x25, 0xd2,
	0x15, 0xb3, 0xa2, 0xf8, 0x38, 0xd5, 0x8f, 0xfd, 0xf4, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x5b,
	0xa2, 0x60, 0x05, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactServiceClient is the client API for ContactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactServiceClient interface {
	AddContact(ctx context.Context, in *AddContactReq, opts ...grpc.CallOption) (*AddContactRep, error)
	GetContact(ctx context.Context, in *GetContactReq, opts ...grpc.CallOption) (*Contact, error)
	SearchContact(ctx context.Context, in *SearchContactReq, opts ...grpc.CallOption) (*ContactList, error)
}

type contactServiceClient struct {
	cc *grpc.ClientConn
}

func NewContactServiceClient(cc *grpc.ClientConn) ContactServiceClient {
	return &contactServiceClient{cc}
}

func (c *contactServiceClient) AddContact(ctx context.Context, in *AddContactReq, opts ...grpc.CallOption) (*AddContactRep, error) {
	out := new(AddContactRep)
	err := c.cc.Invoke(ctx, "/ContactService/AddContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) GetContact(ctx context.Context, in *GetContactReq, opts ...grpc.CallOption) (*Contact, error) {
	out := new(Contact)
	err := c.cc.Invoke(ctx, "/ContactService/GetContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) SearchContact(ctx context.Context, in *SearchContactReq, opts ...grpc.CallOption) (*ContactList, error) {
	out := new(ContactList)
	err := c.cc.Invoke(ctx, "/ContactService/SearchContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactServiceServer is the server API for ContactService service.
type ContactServiceServer interface {
	AddContact(context.Context, *AddContactReq) (*AddContactRep, error)
	GetContact(context.Context, *GetContactReq) (*Contact, error)
	SearchContact(context.Context, *SearchContactReq) (*ContactList, error)
}

func RegisterContactServiceServer(s *grpc.Server, srv ContactServiceServer) {
	s.RegisterService(&_ContactService_serviceDesc, srv)
}

func _ContactService_AddContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContactReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).AddContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContactService/AddContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).AddContact(ctx, req.(*AddContactReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_GetContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).GetContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContactService/GetContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).GetContact(ctx, req.(*GetContactReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_SearchContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchContactReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).SearchContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContactService/SearchContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).SearchContact(ctx, req.(*SearchContactReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ContactService",
	HandlerType: (*ContactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddContact",
			Handler:    _ContactService_AddContact_Handler,
		},
		{
			MethodName: "GetContact",
			Handler:    _ContactService_GetContact_Handler,
		},
		{
			MethodName: "SearchContact",
			Handler:    _ContactService_SearchContact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contact/contact.proto",
}
